-- schema.sql (HSQLDB) - fixed: identity starts at 1

CREATE TABLE app_user
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    first_name VARCHAR(50)  NOT NULL,
    last_name  VARCHAR(50)  NOT NULL,
    email      VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE task
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    due_date    DATE,
    priority    VARCHAR(20),
    status      VARCHAR(20),
    created_by  INTEGER,
    CONSTRAINT fk_task_created_by
        FOREIGN KEY (created_by) REFERENCES app_user (id)
            ON DELETE SET NULL
            ON UPDATE CASCADE
);

